#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cyrus-sasl
Version  : 2.1.27.nodlcompatorsrp
Release  : 13
URL      : https://src.fedoraproject.org/repo/pkgs/rpms/cyrus-sasl/cyrus-sasl-2.1.27-nodlcompatorsrp.tar.gz/sha512/86c45f729d5cf0aacc20c880d1cea5d927536c602d5d5866838036f00babfd5b89cb94d14a2c6ca4d78073f8f5c08da0f1f64a9a32b26c5f1e28b0d9246fd38e/cyrus-sasl-2.1.27-nodlcompatorsrp.tar.gz
Source0  : https://src.fedoraproject.org/repo/pkgs/rpms/cyrus-sasl/cyrus-sasl-2.1.27-nodlcompatorsrp.tar.gz/sha512/86c45f729d5cf0aacc20c880d1cea5d927536c602d5d5866838036f00babfd5b89cb94d14a2c6ca4d78073f8f5c08da0f1f64a9a32b26c5f1e28b0d9246fd38e/cyrus-sasl-2.1.27-nodlcompatorsrp.tar.gz
Source1  : saslauthd.service
Summary  : SASL API implementation
Group    : Development/Tools
License  : BSD-3-Clause-Attribution OpenSSL
Requires: cyrus-sasl-bin = %{version}-%{release}
Requires: cyrus-sasl-lib = %{version}-%{release}
Requires: cyrus-sasl-license = %{version}-%{release}
Requires: cyrus-sasl-man = %{version}-%{release}
Requires: cyrus-sasl-services = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : Sphinx
BuildRequires : buildreq-cpan
BuildRequires : gdbm-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(com_err)
BuildRequires : pkgconfig(krb5)
BuildRequires : pkgconfig(openssl)
Patch1: cyrus-sasl-no_rpath.patch
Patch2: CVE-2019-19906.patch

%description
This is an implemention of the SASL API, useful for adding
authentication, authorization, and security to network protocols.  The
SASL protocol itself is documented in rfc2222; the API standard is a
work in progress.

%package bin
Summary: bin components for the cyrus-sasl package.
Group: Binaries
Requires: cyrus-sasl-license = %{version}-%{release}
Requires: cyrus-sasl-services = %{version}-%{release}

%description bin
bin components for the cyrus-sasl package.


%package dev
Summary: dev components for the cyrus-sasl package.
Group: Development
Requires: cyrus-sasl-lib = %{version}-%{release}
Requires: cyrus-sasl-bin = %{version}-%{release}
Provides: cyrus-sasl-devel = %{version}-%{release}
Requires: cyrus-sasl = %{version}-%{release}

%description dev
dev components for the cyrus-sasl package.


%package lib
Summary: lib components for the cyrus-sasl package.
Group: Libraries
Requires: cyrus-sasl-license = %{version}-%{release}

%description lib
lib components for the cyrus-sasl package.


%package license
Summary: license components for the cyrus-sasl package.
Group: Default

%description license
license components for the cyrus-sasl package.


%package man
Summary: man components for the cyrus-sasl package.
Group: Default

%description man
man components for the cyrus-sasl package.


%package services
Summary: services components for the cyrus-sasl package.
Group: Systemd services

%description services
services components for the cyrus-sasl package.


%prep
%setup -q -n cyrus-sasl-2.1.27
cd %{_builddir}/cyrus-sasl-2.1.27
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582071577
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%reconfigure --disable-static --with-rc4=no \
--with-configdir=/usr/lib/sasl2:/etc/sasl2 \
--disable-java \
--disable-krb4 \
--enable-gssapi \
--with-gss_impl=mit \
--with-saslauthd=/run/saslauthd \
--with-devrandom=/dev/urandom \
--enable-anon \
--enable-cram \
--enable-digest \
--enable-ntlm \
--enable-plain \
--enable-login \
--enable-alwaystrue \
--enable-httpform \
--disable-sql \
--with-dblib=gdbm
make

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 check

%install
export SOURCE_DATE_EPOCH=1582071577
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cyrus-sasl
cp %{_builddir}/cyrus-sasl-2.1.27/COPYING %{buildroot}/usr/share/package-licenses/cyrus-sasl/86af2c4321b2d4b4f092b31fd897444a701c0085
cp %{_builddir}/cyrus-sasl-2.1.27/mac/libdes/src/COPYRIGHT %{buildroot}/usr/share/package-licenses/cyrus-sasl/abf2d0fe9fda25370257deb68b2d851533d1e177
cp %{_builddir}/cyrus-sasl-2.1.27/saslauthd/COPYING %{buildroot}/usr/share/package-licenses/cyrus-sasl/d577bf4daf10875d3b56449ae8cca20aaf86ff05
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/saslauthd.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pluginviewer
/usr/bin/saslauthd
/usr/bin/sasldblistusers2
/usr/bin/saslpasswd2
/usr/bin/testsaslauthd

%files dev
%defattr(-,root,root,-)
/usr/include/sasl/hmac-md5.h
/usr/include/sasl/md5.h
/usr/include/sasl/md5global.h
/usr/include/sasl/prop.h
/usr/include/sasl/sasl.h
/usr/include/sasl/saslplug.h
/usr/include/sasl/saslutil.h
/usr/lib64/libsasl2.so
/usr/lib64/pkgconfig/libsasl2.pc
/usr/share/man/man3/sasl.3
/usr/share/man/man3/sasl_authorize_t.3
/usr/share/man/man3/sasl_auxprop.3
/usr/share/man/man3/sasl_auxprop_getctx.3
/usr/share/man/man3/sasl_auxprop_request.3
/usr/share/man/man3/sasl_callbacks.3
/usr/share/man/man3/sasl_canon_user_t.3
/usr/share/man/man3/sasl_chalprompt_t.3
/usr/share/man/man3/sasl_checkapop.3
/usr/share/man/man3/sasl_checkpass.3
/usr/share/man/man3/sasl_client_init.3
/usr/share/man/man3/sasl_client_new.3
/usr/share/man/man3/sasl_client_start.3
/usr/share/man/man3/sasl_client_step.3
/usr/share/man/man3/sasl_decode.3
/usr/share/man/man3/sasl_dispose.3
/usr/share/man/man3/sasl_done.3
/usr/share/man/man3/sasl_encode.3
/usr/share/man/man3/sasl_encodev.3
/usr/share/man/man3/sasl_errdetail.3
/usr/share/man/man3/sasl_errors.3
/usr/share/man/man3/sasl_errstring.3
/usr/share/man/man3/sasl_getconfpath_t.3
/usr/share/man/man3/sasl_getopt_t.3
/usr/share/man/man3/sasl_getpath_t.3
/usr/share/man/man3/sasl_getprop.3
/usr/share/man/man3/sasl_getrealm_t.3
/usr/share/man/man3/sasl_getsecret_t.3
/usr/share/man/man3/sasl_getsimple_t.3
/usr/share/man/man3/sasl_global_listmech.3
/usr/share/man/man3/sasl_idle.3
/usr/share/man/man3/sasl_listmech.3
/usr/share/man/man3/sasl_log_t.3
/usr/share/man/man3/sasl_server_init.3
/usr/share/man/man3/sasl_server_new.3
/usr/share/man/man3/sasl_server_start.3
/usr/share/man/man3/sasl_server_step.3
/usr/share/man/man3/sasl_server_userdb_checkpass_t.3
/usr/share/man/man3/sasl_server_userdb_setpass_t.3
/usr/share/man/man3/sasl_setpass.3
/usr/share/man/man3/sasl_setprop.3
/usr/share/man/man3/sasl_user_exists.3
/usr/share/man/man3/sasl_verifyfile_t.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsasl2.so.3
/usr/lib64/libsasl2.so.3.0.0
/usr/lib64/sasl2/libanonymous.so
/usr/lib64/sasl2/libanonymous.so.3
/usr/lib64/sasl2/libanonymous.so.3.0.0
/usr/lib64/sasl2/libcrammd5.so
/usr/lib64/sasl2/libcrammd5.so.3
/usr/lib64/sasl2/libcrammd5.so.3.0.0
/usr/lib64/sasl2/libdigestmd5.so
/usr/lib64/sasl2/libdigestmd5.so.3
/usr/lib64/sasl2/libdigestmd5.so.3.0.0
/usr/lib64/sasl2/libgs2.so
/usr/lib64/sasl2/libgs2.so.3
/usr/lib64/sasl2/libgs2.so.3.0.0
/usr/lib64/sasl2/libgssapiv2.so
/usr/lib64/sasl2/libgssapiv2.so.3
/usr/lib64/sasl2/libgssapiv2.so.3.0.0
/usr/lib64/sasl2/liblogin.so
/usr/lib64/sasl2/liblogin.so.3
/usr/lib64/sasl2/liblogin.so.3.0.0
/usr/lib64/sasl2/libntlm.so
/usr/lib64/sasl2/libntlm.so.3
/usr/lib64/sasl2/libntlm.so.3.0.0
/usr/lib64/sasl2/libotp.so
/usr/lib64/sasl2/libotp.so.3
/usr/lib64/sasl2/libotp.so.3.0.0
/usr/lib64/sasl2/libplain.so
/usr/lib64/sasl2/libplain.so.3
/usr/lib64/sasl2/libplain.so.3.0.0
/usr/lib64/sasl2/libsasldb.so
/usr/lib64/sasl2/libsasldb.so.3
/usr/lib64/sasl2/libsasldb.so.3.0.0
/usr/lib64/sasl2/libscram.so
/usr/lib64/sasl2/libscram.so.3
/usr/lib64/sasl2/libscram.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cyrus-sasl/86af2c4321b2d4b4f092b31fd897444a701c0085
/usr/share/package-licenses/cyrus-sasl/abf2d0fe9fda25370257deb68b2d851533d1e177
/usr/share/package-licenses/cyrus-sasl/d577bf4daf10875d3b56449ae8cca20aaf86ff05

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/pluginviewer.8
/usr/share/man/man8/saslauthd.8
/usr/share/man/man8/sasldblistusers2.8
/usr/share/man/man8/saslpasswd2.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/saslauthd.service
