#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cyrus-sasl
Version  : 2.1.27.rc7.nodlcompatorsrp
Release  : 4
URL      : https://src.fedoraproject.org/repo/pkgs/rpms/cyrus-sasl/cyrus-sasl-2.1.27-rc7-nodlcompatorsrp.tar.gz/sha512/8ecb21e82b2ca51bbc5ae08b2b68f63e5e6abdd5c8990cd30da3d35a5c6778689a7670769cddb1dca2d86c07a0316fb86ed18ac139e6b2586d880c9cce4b9a64/cyrus-sasl-2.1.27-rc7-nodlcompatorsrp.tar.gz
Source0  : https://src.fedoraproject.org/repo/pkgs/rpms/cyrus-sasl/cyrus-sasl-2.1.27-rc7-nodlcompatorsrp.tar.gz/sha512/8ecb21e82b2ca51bbc5ae08b2b68f63e5e6abdd5c8990cd30da3d35a5c6778689a7670769cddb1dca2d86c07a0316fb86ed18ac139e6b2586d880c9cce4b9a64/cyrus-sasl-2.1.27-rc7-nodlcompatorsrp.tar.gz
Source1  : saslauthd.service
Summary  : SASL API implementation
Group    : Development/Tools
License  : BSD-3-Clause-Attribution OpenSSL
Requires: cyrus-sasl-bin
Requires: cyrus-sasl-lib
Requires: cyrus-sasl-config
Requires: cyrus-sasl-license
Requires: cyrus-sasl-man
BuildRequires : Linux-PAM-dev
BuildRequires : Sphinx
BuildRequires : buildreq-cpan
BuildRequires : db-dev
BuildRequires : gdbm-dev
BuildRequires : krb5-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(krb5)
BuildRequires : pkgconfig(openssl)
Patch1: cyrus-sasl-no_rpath.patch

%description
This is an implemention of the SASL API, useful for adding
authentication, authorization, and security to network protocols.  The
SASL protocol itself is documented in rfc2222; the API standard is a
work in progress.

%package bin
Summary: bin components for the cyrus-sasl package.
Group: Binaries
Requires: cyrus-sasl-config
Requires: cyrus-sasl-license
Requires: cyrus-sasl-man

%description bin
bin components for the cyrus-sasl package.


%package config
Summary: config components for the cyrus-sasl package.
Group: Default

%description config
config components for the cyrus-sasl package.


%package dev
Summary: dev components for the cyrus-sasl package.
Group: Development
Requires: cyrus-sasl-lib
Requires: cyrus-sasl-bin
Provides: cyrus-sasl-devel

%description dev
dev components for the cyrus-sasl package.


%package lib
Summary: lib components for the cyrus-sasl package.
Group: Libraries
Requires: cyrus-sasl-license

%description lib
lib components for the cyrus-sasl package.


%package license
Summary: license components for the cyrus-sasl package.
Group: Default

%description license
license components for the cyrus-sasl package.


%package man
Summary: man components for the cyrus-sasl package.
Group: Default

%description man
man components for the cyrus-sasl package.


%prep
%setup -q -n cyrus-sasl-2.1.27
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535664371
%reconfigure --disable-static --with-rc4=no \
--with-configdir=/usr/lib/sasl2:/etc/sasl2 \
--disable-java \
--disable-krb4 \
--enable-gssapi \
--with-gss_impl=mit \
--with-saslauthd=/run/saslauthd \
--with-devrandom=/dev/urandom \
--enable-anon \
--enable-cram \
--enable-digest \
--enable-ntlm \
--enable-plain \
--enable-login \
--enable-alwaystrue \
--enable-httpform \
--disable-sql
make

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 check

%install
export SOURCE_DATE_EPOCH=1535664371
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/cyrus-sasl
cp COPYING %{buildroot}/usr/share/doc/cyrus-sasl/COPYING
cp mac/libdes/src/COPYRIGHT %{buildroot}/usr/share/doc/cyrus-sasl/mac_libdes_src_COPYRIGHT
cp saslauthd/COPYING %{buildroot}/usr/share/doc/cyrus-sasl/saslauthd_COPYING
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/saslauthd.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pluginviewer
/usr/bin/saslauthd
/usr/bin/sasldblistusers2
/usr/bin/saslpasswd2
/usr/bin/testsaslauthd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/saslauthd.service

%files dev
%defattr(-,root,root,-)
/usr/include/sasl/hmac-md5.h
/usr/include/sasl/md5.h
/usr/include/sasl/md5global.h
/usr/include/sasl/prop.h
/usr/include/sasl/sasl.h
/usr/include/sasl/saslplug.h
/usr/include/sasl/saslutil.h
/usr/lib64/libsasl2.so
/usr/lib64/pkgconfig/libsasl2.pc
/usr/share/man/man3/sasl.3
/usr/share/man/man3/sasl_authorize_t.3
/usr/share/man/man3/sasl_auxprop.3
/usr/share/man/man3/sasl_auxprop_getctx.3
/usr/share/man/man3/sasl_auxprop_request.3
/usr/share/man/man3/sasl_callbacks.3
/usr/share/man/man3/sasl_canon_user_t.3
/usr/share/man/man3/sasl_chalprompt_t.3
/usr/share/man/man3/sasl_checkapop.3
/usr/share/man/man3/sasl_checkpass.3
/usr/share/man/man3/sasl_client_init.3
/usr/share/man/man3/sasl_client_new.3
/usr/share/man/man3/sasl_client_start.3
/usr/share/man/man3/sasl_client_step.3
/usr/share/man/man3/sasl_decode.3
/usr/share/man/man3/sasl_dispose.3
/usr/share/man/man3/sasl_done.3
/usr/share/man/man3/sasl_encode.3
/usr/share/man/man3/sasl_encodev.3
/usr/share/man/man3/sasl_errdetail.3
/usr/share/man/man3/sasl_errors.3
/usr/share/man/man3/sasl_errstring.3
/usr/share/man/man3/sasl_getconfpath_t.3
/usr/share/man/man3/sasl_getopt_t.3
/usr/share/man/man3/sasl_getpath_t.3
/usr/share/man/man3/sasl_getprop.3
/usr/share/man/man3/sasl_getrealm_t.3
/usr/share/man/man3/sasl_getsecret_t.3
/usr/share/man/man3/sasl_getsimple_t.3
/usr/share/man/man3/sasl_global_listmech.3
/usr/share/man/man3/sasl_idle.3
/usr/share/man/man3/sasl_listmech.3
/usr/share/man/man3/sasl_log_t.3
/usr/share/man/man3/sasl_server_init.3
/usr/share/man/man3/sasl_server_new.3
/usr/share/man/man3/sasl_server_start.3
/usr/share/man/man3/sasl_server_step.3
/usr/share/man/man3/sasl_server_userdb_checkpass_t.3
/usr/share/man/man3/sasl_server_userdb_setpass_t.3
/usr/share/man/man3/sasl_setpass.3
/usr/share/man/man3/sasl_setprop.3
/usr/share/man/man3/sasl_user_exists.3
/usr/share/man/man3/sasl_verifyfile_t.3

%files lib
%defattr(-,root,root,-)
/usr/lib/sasl2/libanonymous.so
/usr/lib/sasl2/libanonymous.so.3
/usr/lib/sasl2/libanonymous.so.3.0.0
/usr/lib/sasl2/libcrammd5.so
/usr/lib/sasl2/libcrammd5.so.3
/usr/lib/sasl2/libcrammd5.so.3.0.0
/usr/lib/sasl2/libdigestmd5.so
/usr/lib/sasl2/libdigestmd5.so.3
/usr/lib/sasl2/libdigestmd5.so.3.0.0
/usr/lib/sasl2/liblogin.so
/usr/lib/sasl2/liblogin.so.3
/usr/lib/sasl2/liblogin.so.3.0.0
/usr/lib/sasl2/libntlm.so
/usr/lib/sasl2/libntlm.so.3
/usr/lib/sasl2/libntlm.so.3.0.0
/usr/lib/sasl2/libotp.so
/usr/lib/sasl2/libotp.so.3
/usr/lib/sasl2/libotp.so.3.0.0
/usr/lib/sasl2/libplain.so
/usr/lib/sasl2/libplain.so.3
/usr/lib/sasl2/libplain.so.3.0.0
/usr/lib/sasl2/libsasldb.so
/usr/lib/sasl2/libsasldb.so.3
/usr/lib/sasl2/libsasldb.so.3.0.0
/usr/lib/sasl2/libscram.so
/usr/lib/sasl2/libscram.so.3
/usr/lib/sasl2/libscram.so.3.0.0
/usr/lib64/libsasl2.so.3
/usr/lib64/libsasl2.so.3.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/cyrus-sasl/COPYING
/usr/share/doc/cyrus-sasl/mac_libdes_src_COPYRIGHT
/usr/share/doc/cyrus-sasl/saslauthd_COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/pluginviewer.8
/usr/share/man/man8/saslauthd.8
/usr/share/man/man8/sasldblistusers2.8
/usr/share/man/man8/saslpasswd2.8
